name: Static Analysis -- Golang
run-name: 'Static Analysis -- Golang -- ${{ gitea.repository }} ${{ gitea.ref_name }} ${{ gitea.sha }}'
on: 
  push:
    branches:
    - '*'

jobs: 
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Initialize Runner
        uses: actions/setup-go@v7
        with: 
          go-version-file: 'go.mod'
      
      - name: Initialize Go
        run: make build-web && go get .

      - name: Run Go Vet
        id: static_govet
        if: always()
        run: go vet ./...

      - name: Verify Static Analysis
        if: >
          steps.static_govet.outcome  != 'success'
        run: exit 1