name: Code Style -- Web Components
run-name: 'Code Style -- Web Components -- ${{ gitea.repository }} ${{ gitea.ref_name }} ${{ gitea.sha }}'
on: 
  push:
    branches:
    - '*'

jobs: 
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
        
      - name: Initialize Runner
        uses: actions/setup-node@v4

      - name: Install Linters
        run: |
          npm install --no-save \
            @eslint/eslintrc \
            @eslint/js \
            eslint \
            globals \
            html-validate \
            stylelint \
            stylelint-config-standard

      - name: Verify Linters
        run: |
          npx html-validate --version
          npx stylelint --version
          npx eslint --version

      - name: Run HTMLValidate
        id: html_lint
        run: npx html-validate --config dev_config/.htmlvalidate.json 'web/html/**/*'

      - name: Run Stylelint
        id: style_lint
        if: always()
        run: npx stylelint --config dev_config/.stylelintrc.json --formatter verbose --fix 'web/css/**/*.css'

      - name: Run ESLint
        id: js_lint
        if: always()
        env:
          DEBUG: eslint:cli-engine
        run: npx eslint --config dev_config/eslint.config.mjs --fix web/scripts/

      - name: Verify Linters
        if: >
          steps.html_lint.outcome  != 'success' ||
          steps.style_lint.outcome != 'success' ||
          steps.js_lint.outcome    != 'success'
        run: exit 1